[package]
name = "rust-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom7 = { version = "7.0", package = "nom" }

[dev-dependencies]
test-case = "1"
